### ISSUE TITLE
Do you have a project on flask with sqlalchemy and vue.js as frontend?

### ISSUE THREAD

**Issue by rlam3** [yymm/flask-vuejs#4]
Do you have a project on flask with sqlalchemy/backend and vue.js as frontend?

**Comment by jelofen** [comment]
My project used flask and vuejs and mongodb. but now for SEO reasons we use
nuxt js insted of vue js.

**Comment by yymm** [comment]
No, but I can make a simple example and add it.

Do you want it?

**Comment by rlam3** [comment]
SEO reasons? meaning the nuxt.config.js is nicer to work with? @jelofen 
@yymm yes please. Would love for you to share the link with us :)

**Comment by yymm** [comment]
OK, please wait as it may take a while.

**Comment by jelofen** [comment]
As you probably know, nuxt js is server side rendering for vue js and
search engines can track it better since data is already ready when the
page leads. I used it for my magazine in this project to test the features
and get the hang of it. the rest of project uses django mongodb for backend
and does not use vue js. but we are planning to switch to vue js (nuxt js)
as soon as we deal with some of our new challenges.

the link that uses nuxt js: https://ekhodro.com/mag/

the website is in Farsi, but you can easily see that it is a single page
application that uses vue js (nuxt js).

your code helped us a lot at the beginning of this project. I hope you
continue your nice work to help other people as well. for people who use
mongodb you can also recommend "python eve", I am learning eve  and i think
it adds some nice features to have a rest api in flask.

thank you very much

**Comment by yymm** [comment]
SQLAlchemy's simple example done => 3e02645b4984ed39b79c699ec5aa3f67a2747032

At the same time, as you can see the demo with Heroku, please refer to that as well.

[SQLAlchemy simple example - flask-vue.js](https://flaskvuejs.herokuapp.com/sqlalchemy "flask-vue.js")

I am pleased that this project is useful for someone :)

Thank you.

**Comment by rlam3** [comment]
@yymm this is amazing! Thanks!
